os: Visual Studio 2015
configuration: release
install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

before_build:
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  - cmd: powershell ./build/UpdateAssemblyVersions.ps1 "%GitVersion_NuGetVersion%"
  - cmd: dotnet restore

build:
  project: SimpleParameterValidation.sln

after_build:
  - cmd: dotnet pack ./src/SimpleParameterValidator -c "%CONFIGURATION%" -o ./publish
  - cmd: appveyor PushArtifact "./publish/SimpleParameterValidator.%GitVersion_NuGetVersion%.nupkg"

test_script:
- cmd: dotnet test ./tests/SimpleParameterValidator.UnitTests